# Site settings
title: Mithun Diddi's Portfolio Site
email: mail@mithundiddi.com
description: >
baseurl: "" # the subpath of your site
url: "https://mithundiddi.com" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag